version: '3.8'

services:
  
  # Django Web Application
  
  web:
    build: .
    container_name: finance_api_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app                   
    ports:
      - "8000:8000"               
    env_file:
      - .env                      
    depends_on:
      - db
      - redis

  
  # PostgreSQL Database
  
  db:
    image: postgres:15-alpine
    container_name: finance_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  
  # Redis (Message Broker for Celery)
  
  redis:
    image: redis:7-alpine
    container_name: finance_api_redis

  
  # Celery Worker
  
  celery_worker:
    build: .
    container_name: finance_api_celery_worker
    command: python -m celery -A Finance_Management.celery worker --loglevel=info -P solo
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  # Celery Beat (Task Scheduler)
  
  celery_beat:
    build: .
    container_name: finance_api_celery_beat
    command: python -m celery -A Finance_Management.celery beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db


# Named Volumes

volumes:
  postgres_data:
